### ISSUE TITLE
Crash With Galacticraft

### ISSUE THREAD

**Issue by kenijey** [Quetzi/Morpheus#36] opened 2017-05-02 16:15 UTC
https://github.com/micdoodle8/Galacticraft/issues/2671
thanks...

**Comment by Quetzi** [comment] 2017-05-02 16:33
Duplicate of #21, #31, #32, #33, #34, #35 this is a sponge bug. To fix, remove sponge.

**Closed by Quetzi** 2017-05-02 16:33 UTC

**Comment by kenijey** [comment] 2017-05-02 16:37
oh...
