### ISSUE TITLE
server tick loop

### ISSUE THREAD

**Issue by YOYOK9** [Quetzi/Morpheus#32] opened 2017-03-28 23:38 UTC
Seemed when ever a player tried to go to the end the server would crash. Currently trying to see what happens after resetting the end. However Seems to be a weird problem if it is the end causing the crash? Since there's no "day/night" in the end Dim.

Morpheus-1.10.2-3.1.13
https://pastebin.com/Gjq66jxe

**Comment by Quetzi** [comment] 2017-03-29 00:23
Duplicate of #31 Sponge bug

**Closed by Quetzi** 2017-03-29 00:23 UTC

**Comment by YOYOK9** [comment] 2017-03-29 00:44
Ah. Makes sense, Seems they messed up a few mods
