### ISSUE TITLE
1.11.2 - [Server thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [Quetzi/Morpheus#28] opened 2017-01-20 02:53 UTC
https://gist.github.com/ProsperCraft/4635338b9ec5268f25b764626e6795fd

Log excerpt-

Players were unable to open chests or click on crafting tables, I checked the console and found this.

Removing the mod fixed the issue.

**Comment by Quetzi** [comment] 2017-01-20 03:13
Guarantee that this is nothing to do with me. Need a little more info if there is going to be any chance of tracking this down. Looking at the console excerpts you have some very 'rough' mods in there as there appears to be a bunch of  stdout 'logging' in there for simple forge events.  Concurrent Execution Exception basically means you have another thread touching the same stuff that Morpheus is at the same time. If I had to guess I'd say you are running a sponge server which is not something I can support unfortunately, at least not without a proper log, I need more info about the environment this happens in instead of just trying to guess about it.

**Comment by ProsperCraft** [comment] 2017-01-20 03:27
I am not running a sponge server for this pack(because its in testing) specifically so I don't get the "its sponge not us".

forge-1.11.2-13.20.0.2223-universal  - only....no sponge.  This is upgraded from the pack default so we could add your mod.

The modpack is called Elf Squared on the curse launcher- https://mods.curse.com/modpacks/minecraft/256325-one-elf-squared

**Comment by Quetzi** [comment] 2017-01-20 03:36
Can't even begin to track down which mod is causing the problem from that info, sorry. My only advice for tracking this down would be to start removing mods that you think could be clashing with Morpheus until you find the culprit. I'm closing this issue though as I'm satisfied that the problem isn't in my code based on the limited information you've given me. I'm happy to reopen should that not be the case.

**Closed by Quetzi** 2017-01-20 03:36 UTC

**Comment by kreezxil** [comment] 2017-01-20 11:41
Hey Quetzi, I'm the creator of the Modpack that Prospercraft created this bug report for. So, I setup a test server, removed all of the mods, made sure the server and the test client also with no mods were both on build 2223. Then on the test server I installed just your mod so that it was the only mod in the entire game.

Got the following when accessing crafting tables and chests. Basically anything with a gui.

Latest Log: https://gist.github.com/962fab12b08ef60e71b9fe5a6c940ef9
FML Server Latest: https://gist.github.com/8944678a74b02f14e331e800c89cb32e

If you need any help running experiemental builds keep in mind I have a test server setup with your 1 mod in it.

Cheers!

**Comment by Quetzi** [comment] 2017-01-20 12:07
New build is available on Curse now: https://minecraft.curseforge.com/projects/morpheus/files/2370852 let me know if it helps

**Comment by kreezxil** [comment] 2017-01-20 13:45
Thank you! That works fine without issues.
