### ISSUE TITLE
1.7.10-1.6.18 Crash

### ISSUE THREAD

**Issue by tgstyle** [Quetzi/Morpheus#14] opened 2015-11-30 17:00 UTC
This is when logging in to a server that has the night cycles disabled in NEI (as OP).

https://gist.github.com/tgstyle/b8663d79499e46be47d7

**Comment by Quetzi** [comment] 2016-12-19 15:50
Closing as I was never able to reproduce this and the codebase has changed quite a bit since this issue was raised. If the issue persists on the latest builds feel free to reopen.

**Closed by Quetzi** 2016-12-19 15:50 UTC
