### ISSUE TITLE
SMP crash when going through portals

### ISSUE THREAD

**Issue by LemADEC** [Quetzi/Morpheus#33] opened 2017-03-29 00:52 UTC
As of 
forge-1.10.2-12.18.3.2254-universal.jar
Morpheus-1.10.2-3.1.12.jar
VoidCraft-1.10.2-0.17.8.jar
server crashes intermittently when player goes through the void portal from the overworld:
```
[20:28:19] [Server thread/INFO] [journeymap/]: §1Bolt_theif§r joining dimension -2
[20:28:20] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@37b08eb:
java.lang.NullPointerException
        at net.quetzi.morpheus.helpers.SleepChecker.updatePlayerStates(SleepChecker.java:28) ~[SleepChecker.class:?]
        at net.quetzi.morpheus.helpers.MorpheusEventHandler.worldTickEvent(MorpheusEventHandler.java:81) ~[MorpheusEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_682_MorpheusEventHandler_worldTickEvent_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[20:28:20] [Server thread/ERROR] [FML/]: Index: 14 Listeners:
[20:28:20] [Server thread/ERROR] [FML/]: 0: NORMAL
[20:28:20] [Server thread/ERROR] [FML/]: 1: ASM: am2.proxy.tick.ServerTickHandler@5caa70f8 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 2: ASM: WayofTime.bloodmagic.util.handler.event.WillHandler@4d005f41 onServerWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 3: ASM: lumien.bloodmoon.handler.BloodmoonEventHandler@384128c endWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 4: ASM: ItemGrassSeeds{Name=grassSeeds} onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 5: ASM: ItemTerraAxe{Name=terraAxe} onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 6: ASM: feyberryjam.minecraft.druidry.init.ModEvents@7bd83fef onWorldTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 7: ASM: atomicstryker.infernalmobs.common.InfernalMobsCore@7c376ef6 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 8: ASM: lycanite.lycanitesmobs.core.mobevent.MobEventManager@3bce3840 onWorldUpdate(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 9: ASM: shadowfox.botanicaladdons.common.items.travel.stones.ItemWaystone$Companion@77dee144 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEven$
[20:28:20] [Server thread/ERROR] [FML/]: 10: ASM: shadowfox.botanicaladdons.common.block.dendrics.thunder.ThunderEventHandler@75632ffc catchWorldTick(Lnet/minecraftforge/fml/common/gameevent/Tick$
[20:28:20] [Server thread/ERROR] [FML/]: 11: ASM: class vazkii.botania.common.core.handler.CommonTickHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 12: ASM: de.teamlapen.vampirism.core.ModEventHandler@4f179442 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 13: ASM: Tamaized.Voidcraft.events.ItemEntityEvent@63c609e9 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 14: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@2bb5626b worldTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 15: ASM: Block{botania:pistonRelay} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 16: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@522414a9 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 17: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@65acb828 tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:28:20] [Server thread/ERROR] [FML/]: 18: ASM: com.creativemd.creativecore.event.GuiTickHandler@3abd7dc2 onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:28:20] [Server thread/TRACE] [ArsMagica2/]: Saving all cached power data for DIM -1 to disk
```

**Comment by Quetzi** [comment] 2017-03-29 01:16
Duplicate of #32 #31 and #21

**Closed by Quetzi** 2017-03-29 01:16 UTC

**Comment by LemADEC** [comment] 2017-03-29 01:54
https://github.com/SpongePowered/SpongeForge/issues/830
