### ISSUE TITLE
Exception in TickLoop Crash

### ISSUE THREAD

**Issue by KappaKiddie** [Quetzi/Morpheus#35] opened 2017-04-30 15:48 UTC
https://pastebin.com/90xCHFxX

**Comment by Quetzi** [comment] 2017-04-30 16:44
Duplicate of #21, #31, #32, #33, #34 this is a sponge bug. To fix, remove sponge.

https://github.com/SpongePowered/SpongeForge/issues/830

**Closed by Quetzi** 2017-04-30 16:44 UTC
