### ISSUE TITLE
[1.12] Mod Crash

### ISSUE THREAD

**Issue by ElectricBlue1** [Quetzi/Morpheus#46] opened 2017-07-19 04:57 UTC
I was loading a new mod pack fro 1.12  and Morpheus crashed... 

Crash: [crash-2017-07-19_00.50.22-client.txt](https://github.com/Quetzi/Morpheus/files/1158045/crash-2017-07-19_00.50.22-client.txt)

**Comment by Quetzi** [comment] 2017-07-19 07:50
Duplicate of #42

**Closed by Quetzi** 2017-07-19 07:50 UTC
